# Generated by Django 4.1.7 on 2023-03-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('disasterNo', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('seq', models.IntegerField()),
                ('group', models.TextField()),
                ('subtype', models.TextField(null=True)),
                ('subgroup', models.TextField(null=True)),
                ('eventName', models.TextField(null=True)),
                ('country', models.TextField()),
                ('iso', models.TextField()),
                ('location', models.TextField()),
                ('startYear', models.IntegerField(null=True)),
                ('startMonth', models.IntegerField(null=True)),
                ('startDay', models.IntegerField(null=True)),
                ('endYear', models.IntegerField(null=True)),
                ('endMonth', models.IntegerField(null=True)),
                ('endDay', models.IntegerField(null=True)),
                ('totalDeaths', models.IntegerField(null=True)),
                ('injured', models.IntegerField(null=True)),
                ('affected', models.IntegerField(null=True)),
                ('totalAffected', models.IntegerField(null=True)),
                ('homeless', models.IntegerField(null=True)),
                ('damageCost', models.IntegerField(null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.continent')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.region')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.type')),
            ],
        ),
    ]
