# Generated by Django 4.1.7 on 2023-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_alter_disaster_startyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='affected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='damageCost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='endDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='endMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='endYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='eventName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='homeless',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='injured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='startDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='startMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='subtype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='totalAffected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='totalDeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
