services:
  - type: web
    name: disaster-info
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn mysite.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true